apiVersion: integration/v1
kind: Trigger
name: event-fired
version: 1
summary:  Datadog Event Trigger
description: |
  This trigger handles Datadog events and notifications

responders:
  - webhook

schemas:
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/datadog-trigger-event-fired

examples:
- summary: When a Datadog event is fired
  content:
    apiVersion: v1
    kind: Trigger
    name: datadog-event
    source:
      type: webhook
      image: relaysh/datadog-trigger-event-fired
    binding:
      parameters:
        id: !Data id
        last_updated: !Data last_updated
        event_type: !Data event_type
        title: !Data title
        date: !Data date
        body: !Data body
