apiVersion: integration/v1
kind: Step
name: incident-extract-id
version: 1
summary: Extract Datadog Incident ID

description: Extracts an internal Incident ID, given its friendly id.
build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/datadog-step-incident-extract-id

examples:
- summary: Extract internal ID for Datadog Incident
  content:
    apiVersion: v1
    kind: Step
    name: extract-id
    image: relaysh/datadog-step-incident-extract-id
    spec:
      connection:  !Connection {type: "datadog", name: "my-datadog-keys"}
      public_id:  !Parameter public_id