apiVersion: integration/v1
kind: Step
name: incident-create
version: 1
summary: Create an incident

description: Creates a new Datadog Incident.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/datadog-step-incident-create

schemas:
  spec: 
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
